### ISSUE TITLE
Which mean file to use?

### ISSUE THREAD

**Issue by waleedka** [metalbubble/places365#13]
The repo contains this mean file:  places365CNN_mean.binaryproto

But in /docker/run_scene.py this line of code seems to imply using the ILSVRC 2012 mean file.

```
transformer.set_mean('data', np.load(
    'python/caffe/imagenet/ilsvrc_2012_mean.npy').mean(1).mean(1))
```

Which is the right one to use?

**Comment by metalbubble** [comment]
It is fine to use it, also you could just use a constant number such as 125. It doesn't really matter.
