### ISSUE TITLE
Places365 Test data ground truth

### ISSUE THREAD

**Issue by TheShadow29** [metalbubble/places365#18]
I wanted to reproduce the results in the paper. Where can I find the ground truth results for the test data set of Places365 Standard? I am currently trying it on small images [http://places2.csail.mit.edu/download.html](http://places2.csail.mit.edu/download.html). 

I have downloaded the image list and annotation file of Places365 as given in [Places365 dev kit](https://github.com/metalbubble/places_devkit), but it only has the file names of the test data set, and not the ground truth.

**Comment by metalbubble** [comment]
Test labels are not released. you need to submit your prediction to http://places2.csail.mit.edu/download.html
