### ISSUE TITLE
Is there a mean.binaryproto file for vgg16_hybrid.model?

### ISSUE THREAD

**Issue by Chrisdy** [metalbubble/places365#3]
only find places365CNN_mean.binaryproto, is there a mean.binaryproto file for vgg16_hybrid.model?

**Comment by metalbubble** [comment]
I used the same places365CNN_mean.binaryproto for vgg16 hybrid training. The mean image really doesn't affect the prediction result.

**Comment by mrgransky** [comment]
Is there any relevance between this closed issue and https://github.com/CSAILVision/places365/issues/74#issue-566447191?
