### ISSUE TITLE
Is there a labels file for validating data?

### ISSUE THREAD

**Issue by dxiaosa** [metalbubble/places365#5]
I downloaded the 'Places365 Development kit', and I found that there were only the 'categories_places365.txt' and 'categories_hybrid1365.txt' for labels file of training data. So, is there a labels file for validating data?

**Comment by shicai** [comment]
see https://github.com/metalbubble/places_devkit/blob/master/data/download_data.sh
run this file to get image lists for your train/val data.

**Comment by micklexqg** [comment]
@shicai, the url is 404...
